name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  # allow external contributions to use secrets within trusted code
  pull_request_target:
    types: [opened, synchronize, closed]
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    # prevent duplicate workflows and only allow one `pull_request` or `pull_request_target` for
    # internal or external contributions respectively
    if: |
      (github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request') ||
      (github.event.pull_request.head.repo.full_name != github.repository && github.event_name == 'pull_request_target')
    secrets: inherit
    with:
      # running on the oldest ubuntu we can to ensure compatibility as glibc would be a problem if we built on latest ubuntu.
      # see: https://tauri.app/v1/guides/building/linux#limitations
      tests_run_on: '["ubuntu-20.04","macos-latest","windows-2019"]'
      restrict_custom_actions: false
      github_prerelease: true
      repo_config: true
      repo_description: "Test Tauri with Flowzone"
